### ISSUE TITLE
Idea: Add a slug for districts

### ISSUE THREAD

**Issue by sjockers** [datenguide/datenguide-backend#3]
I am generating profile pages, currently using the Kreisschlüssel in the URL. It would be great to be able to use a slug based on the district name. I can either generate it and store it statically in the client, or we provide it via the API. Thoughts?

**Comment by simonwoerpel** [comment]
i would provide it through the api to have more consistence (in terms of "source of through") so there are slugs now: https://github.com/datenguide/datenguide-backend/commit/540abcc50d6cd53db95e38ff58decc7e3cc6e02e

todo: think about naming of districts (like "Flensburg" instead of "Flensburg, kreisfreie Stadt")

**Comment by sjockers** [comment]
Perfect! 

> todo: think about naming of districts (like "Flensburg" instead of "Flensburg, kreisfreie Stadt")

Sounds good. Maybe split this into `name` ("Flensburg") and `type` ("kreisfreie Stadt")?

**Comment by sjockers** [comment]
👍🎉
